name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Test Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: potduino-dev:latest
          file: docker/Dockerfile

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: marian-code/python-lint-annotate@v2
        with:
          python-root-list: "src"
          use-black: false
          use-pydocstyle: false
          use-pylint: false
          use-mypy: false

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Requirements
        run: |
          pip install -r ci-requirements.txt
      - name: Build Documentation
        run: |
          bash ./docs/build-doc.sh
      - uses: actions/upload-artifact@v3
        with:
          name: DocumentationHTML
          path: docs/_build/html/
      - name: Sphinx to GitHub Pages
        uses: sphinx-notes/pages@1.0
        if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
        with:
          documentation_path: "docs/source"
      - name: GitHub Push
        if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
