name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Test Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: potduino-dev:latest
          file: docker/Dockerfile
